Update README.md
osevg/workshopper-content pull request #110
Opened 2019-01-28 16:44 UTC by alberttwong

added howto to get the APB into the service catalog.

2019-01-28 17:20 UTC, alberttwong commented
@jankleinert Can you help?  I don't understand why the check failed.

2019-02-04 20:51 UTC, jorgemoralespou requested changes
There's 2 minor things that need to be changed. Also, travis is not configured to push the images the PR generates to dockerhub, hence the error you see. Once merged, it will work. :-D

2019-02-04 20:51 UTC, jorgemoralespou commented on README.md
> +An [APB](https://hub.docker.com/r/openshiftapb/cloudnative-workshop-apb) is provided for
This references another APB. This should be https://hub.docker.com/r/openshiftapb/starter-workshop-apb/

2019-02-04 20:51 UTC, jorgemoralespou commented on README.md
> +## Install the ASB into your Service Catalog
Install the ASB? Isn't these instructions to install the APB? Reading your instructions seems that you expect the ASB (Ansible Service Broker???) to be there

2019-02-04 23:38 UTC, alberttwong commented on README.md
> +## Install the ASB into your Service Catalog
Ooops.  I think I misspelled.

2019-02-04 23:43 UTC, alberttwong commented on README.md
> +An [APB](https://hub.docker.com/r/openshiftapb/cloudnative-workshop-apb) is provided for
fixed

2019-02-04 23:43 UTC, alberttwong commented on README.md
> +## Install the ASB into your Service Catalog
fixed

2019-02-15 19:56 UTC, merged