Minor fixes, image updates, and grammar
osevg/workshopper-content pull request #163
Opened 2020-06-09 16:38 UTC by cedricclyburn

Included grammatical edits, added/replaced extra imagery for context, & small content additions.

2020-06-09 22:06 UTC, btannous commented on workshop/content/parksmap-permissions.adoc
> +Another way you could have done the same is by using the OpenShift console. From the Administrator perspective,navigate to the *Workloads -> Deployment Configs* page, click on the *Namespace*, then *
missing a space!

2020-06-09 22:09 UTC, btannous commented on workshop/content/parksmap-docker.adoc
> +This is incredible easy with OpenShift, and it can be done directly from the web console.
With the explanation of what a container image is (which I like) I lost context of what you mean by `This is incredible easy with OpenShift...`
Also typo.

2020-06-09 22:11 UTC, btannous commented on README.md
> +The deployment created above will use an image from [Quay.io](https://quay.io/) for this workshop, a container automatization platform, based on the ``ocp-4.2`` branch of the repository.
Typo: automation platform.

2020-06-09 22:15 UTC, btannous commented on README.md
> +Once the cluster is deployed, which may take up to 75 minutes, follow the directions in the [Running the Workshop](#running-the-workshop) section to begin the workshop itself.
I think I would put the note that the RHPDS cluster may take 75 minutes to deploy in a line before this one.

It seems odd to say "Once the cluster is deployed, which may take a long time, do this..."
It might be better to do

> *Note:* It will take up to 75 minutes to deploy the OCP4 cluster via RHPDS.

Once the cluster is deployed, follow the...

2020-06-09 22:18 UTC, bttnns requested changes
See the comments inline =) Overall looks awesome though! Thank you for the help =)

2020-06-15 15:43 UTC, cedricclyburn commented
Hey Brian! Thanks for reviewing this, just made those edits :)

2020-06-15 16:03 UTC, bttnns requested changes
Just remove that last part and this looks good!

2020-06-15 16:03 UTC, btannous commented on README.md
> +Once the cluster is deployed, which may take up to 75 minutes, follow the directions in the [Running the Workshop](#running-the-workshop) section to begin the workshop itself.
@cedricclyburn this line still looks like it has the `which may take up to 75 minutes`

2020-06-15 16:03 UTC, btannous commented on README.md
> +**Note:** It will take up to 75 minutes to deploy the OCP4 cluster via RHPDS.
This looks good though!

2020-06-15 18:18 UTC, bttnns approved these changes
Thanks =)

2020-06-15 18:18 UTC, merged